SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES

# SELECT U.USER_ID, U.NICKNAME
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_USER U
# ON B.WRITER_ID = U.USER_ID
# WHERE (USER_ID, PRICE) IN (
#     SELECT A.WRITER_ID, SUM(A.PRICE)
#     FROM USED_GOODS_BOARD A
#     WHERE STATUS = 'DONE'
#     GROUP BY A.WRITER_ID
#     HAVING SUM(A.PRICE) >= 700000
# )
# ORDER BY TOTAL_SALES